### ISSUE TITLE
Unable to install plugin after following authentication instructions

### ISSUE THREAD

**Issue by zuruzirou** [askthecode/documentation#12]
I am attempting to use this plugin for the first time today. I've carefully followed the provided authentication instructions, but I'm encountering an issue where the plugin won't install. Any assistance or insights on resolving this would be greatly appreciated.
![image](https://github.com/askthecode/documentation/assets/483016/66963fb7-4d6e-4f05-886b-d3822c56d3f4)

**Comment by dsomok** [comment]
Hi @zuruzirou,

I wanted to let you know that this is a known issue. It seems to reproduce for some users, not only with the AskTheCode plugin but with others as well.

Could you please let me know if your browser language is set to English? If not, could you try switching it to English and attempt the installation again? I've received reports from multiple users indicating that this might help.

Please ping me if changing the language helps or not.

**Comment by zuruzirou** [comment]
Hi @dsomok, changing the browser language to English worked and resolved the issue. Thank you!
