### ISSUE TITLE
Cancelled subscription, but it keeps trying to charge my credit card

### ISSUE THREAD

**Issue by jeremiah-k** [askthecode/documentation#20]
I cancelled my subscription before my card was charged and it keeps attempting to charge my card, while keeping me on the "Senior" package.

It has tried to charge my card 3 times since Oct 30 when my subscription ran out. 

![image](https://github.com/askthecode/documentation/assets/17190268/0b45213f-385a-4742-b91d-6029ed9af1a3)

**Comment by dsomok** [comment]
Hi @jeremiah-k,

Here is what I can see in the Stripe dashboard:
![image](https://github.com/askthecode/documentation/assets/2426834/f11b04f6-d90e-47c7-87e5-66ce5c8902dd)

So it looks like you've canceled on October 30th after it generated the invoice, so it marked the subscription as the one that cancels in a month (November 30th) and tries to collect the invoice.

No worries, I've canceled your subscription and the automatic payment retries and collection have been switched off:
![image](https://github.com/askthecode/documentation/assets/2426834/1646b0c1-f1bd-46a2-8c6e-6edfa8f63458)

Sorry for the inconveniences!
