### ISSUE TITLE
Paid Plan not recognized

### ISSUE THREAD

**Issue by jfrlnce** [askthecode/documentation#29]
I paid for the senior plan to get more requests but it is not being recognized

[Codbase URL] Study the codebase
GPT
Talked to pluginlab.askthecode.dsomok.online
I have initiated the process to study the codebase at the specified GitHub repository. However, it seems you've reached your free request quota and need to configure your account to proceed further. Please follow this [link](https://c7d59216ee8ec59bda5e51ffc17a994d.auth.portal-pluginlab.ai/user/operations/proceed) to update your account settings and continue with the request. Once your account is configured, we can resume the analysis of the codebase.

User
I am not on the free plan I am on the senior plan
GPT
I apologize for the confusion. Let's try accessing the repository structure again. I will initiate another request to study the codebase at the specified GitHub repository. Please give me a moment.

Talked to pluginlab.askthecode.dsomok.online
It seems there is still an issue with accessing the repository structure under the specified plan. The system is indicating that an account configuration is required. To ensure you can proceed with accessing the codebase and to resolve this matter, please visit the provided [link](https://c7d59216ee8ec59bda5e51ffc17a994d.auth.portal-pluginlab.ai/user/operations/proceed) to check your account details and make any necessary updates.

Once you have verified and adjusted your account settings as needed, we can continue with the analysis. If you believe your account should already have the appropriate access under the senior plan, I recommend checking the account status or contacting support through the provided link for clarification.

**Comment by dsomok** [comment]
hey @jfrlnce,

Thanks for using AskTheCode!

It looks like you are currently signed in under a different account than the one you've purchased the subscription for.

Could you please try to sign out and then sign in again? I've just updated the documentation with information on how to do that:
https://docs.askthecode.ai/authentication/#subscription-quota-not-applied

Please ping me if it resolves the issue or not. If it doesn't help, I'll do further investigation.

Sorry for the inconvenience :(

**Comment by jfrlnce** [comment]
@dsomok

This works thank you.
