### ISSUE TITLE
Authenticating Private Repository 

### ISSUE THREAD

**Issue by nkretz22** [askthecode/documentation#31]
The AskTheCode GPT no longer authenticates to my Github repository. The documentation references how to troubleshoot the plugin, but the plugin no longer exists. How do I authenticate with the GPT?

Here is the message I receive:
Please verify that the URL is correct. Additionally, if the repository is private, ensure you're using GitHub authentication with AskTheCode, and the account being used has access to the requested repository.

**Comment by K33KS** [comment]
I'm having the same issue. I cannot use the account that my subscription is under, and I can no longer re-associate the account since plugins have deprecated.

**Comment by dsomok** [comment]
Hey @nkretz22, @K33KS, sorry for the inconvenience.

From what I can see in the logs, PluginLab is not returning the GitHub token, so the default one is used, and the default token does not have access to your private repositories.

Could you please try to log out and log in once again with your GitHub account? You can find the documentation about how to log out from the GPT [here](https://docs.askthecode.ai/authentication/#subscription-quota-not-applied)

Please ping me if helps or not.

**Comment by nkretz22** [comment]
Thank you for pointing me in the right direction. I logged back in with the Github account and it's working again.

**Comment by dsomok** [comment]
Great, happy to hear that and thanks for the feedback. Sorry for the inconvenience with the need to relogin. 

@K33KS, please test on your side if it helps as well.

**Comment by K33KS** [comment]
That did the trick. Much appreciated!

**Comment by dsomok** [comment]
great, happy to hear that :)
