### ISSUE TITLE
Hello, how do I cancel the renewal service? It keeps deducting my fees.

### ISSUE THREAD

**Issue by lidiancracy** [askthecode/documentation#32]
Hello, how do I cancel the renewal service? It keeps deducting my fees.

**Comment by lidiancracy** [comment]
I found the solution

**Comment by dsomok** [comment]
Hi @lidiancracy, thanks for letting me know. Feel free to reach out in case if you have any questions or need any assistance!
You can do that via my email dsomok.github@gmail.com as well.
