### ISSUE TITLE
Can't refund subscription

### ISSUE THREAD

**Issue by diassique** [askthecode/documentation#34]
Hi. Thanks for making such a great product, but I haven't used it in a while as there is no need for it, I forgot to cancel my subscription and was charged this morning. Is there any way to get those funds back?

**Comment by dsomok** [comment]
Hey @diassique,

Thanks for using AskTheCode and sorry for the long reply!

Sure, I can process the refund for you. Please reach out to me via email at dsomok.github@gmail.com with the details about your account, and I will process it for you.
