### ISSUE TITLE
Unable to query any public repos

### ISSUE THREAD

**Issue by jbmln** [askthecode/documentation#38]
Currently unable to query any public GH or gitlab public repos. This was working yesterday (or day before) and suddenly stopped working. Your documentation discusses uninstalling/reinstalling "plugins" whereas ChatGPT no longer uses the "plugin" nomenclature but rather talks of custom GPTs.

Having googled, plugins seem to have been deprecated in favour of custom GPTs. I'm currently paying askthecode for a service... and currently cannot use it. I don't think it's a client-side issue as a) it was working fine before and b) I've tried it using various clients (iOS app, desktop webapp) and still get the same problem.

Please see attached screenshot of what happens if I ask any question querying a github repo.
![askthecode_screenshot_20240729](https://github.com/user-attachments/assets/336af661-a3c2-4dd0-8a94-c027f912cf21)

Thanks.

**Comment by tastybento** [comment]
Same issue here. Ask TheCode won't open any public repos. I didn't log in using my GitHub account, just used the magic code to the email address. It used to work, but doesn't now.

**Comment by dsomok** [comment]
Hi @jbmln @tastybento

Sorry for the delay with the response. The issue has been found on my side. The configuration was invalid after the latest release and reproduced for all users who used the *Email Authentication*.

Could you please verify that everything works as expected now?

**Comment by jbmln** [comment]
@dsomok - it's working again. Thanks!

**Comment by tastybento** [comment]
Yes, thanks!

**Comment by dsomok** [comment]
happy to hear that, thanks for your feedback and sorry for the inconvenience!
